In [12]:
import numpy as np
a=np.array([[3,4]])
print(a)
a
b=np.array([[2,3,4]])
print(b)
c=np.array([[[3,4,55,6],[2,3,4,5],[2,6,8,5]]])
print(c)
d=np.array([3,4])
print(d)
e=np.array([25,14.5,'hi',True],dtype=object)
print(e)
v=np.zeros((6,5),dtype=int)
print(v)
x=np.ones([2,1])
print(x)
r=np.arange(6,1,-2)
print(r)
t=np.eye(3,4,k=2)
print(t)
c=np.full((4,5),'qubits')
print(c)
np.random.seed(10)
i=np.random.rand(4,5)
print(i)
b=np.random.randint(3,7,(4,5))
print(b)

[[3 4]]
[[2 3 4]]
[[[ 3  4 55  6]
  [ 2  3  4  5]
  [ 2  6  8  5]]]
[3 4]
[25 14.5 'hi' True]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1.]
 [1.]]
[6 4 2]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[['qubits' 'qubits' 'qubits' 'qubits' 'qubits']
 ['qubits' 'qubits' 'qubits' 'qubits' 'qubits']
 ['qubits' 'qubits' 'qubits' 'qubits' 'qubits']
 ['qubits' 'qubits' 'qubits' 'qubits' 'qubits']]
[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
 [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]]
[[4 6 4 5 4]
 [3 5 5 5 4]
 [3 4 6 4 3]
 [6 5 4 4 5]]


In [11]:
import numpy as np
a=np.array([[12,24],[36,48],[60,72]])
print(a)
a.shape
a.ndim


[[12 24]
 [36 48]
 [60 72]]


2

In [2]:
import numpy as np
a=np.array([[2,4,6],[4,6,10]],dtype=int)
a.itemsize

8

In [3]:
import numpy as np
a=np.array([2,3,5,7,9])
print(a)
a[2]=100
print(a)

[2 3 5 7 9]
[  2   3 100   7   9]


In [4]:
import numpy as np
a=np.array([2,3,5,7,9])
print(a)
a[2]=100
print(a)

[2 3 5 7 9]
[  2   3 100   7   9]


In [5]:
import numpy as np
c=np.array([5,10,15,20,25,30])
print(c)
c[0: :5]


[ 5 10 15 20 25 30]


array([ 5, 30])

In [6]:
import numpy as np
a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
import numpy as np
a=np.array([3,4,5,6])
print(a)
print(a.shape)

[3 4 5 6]
(4,)


In [10]:
import numpy as  np
b=np.random.randint(10,50,(3,3))
print(b)

[[33 40 21]
 [38 20 34]
 [19 25 28]]
