In [1]:
import tensorflow


ModuleNotFoundError: No module named 'tensorflow'

In [1]:
import tensorflow 

ModuleNotFoundError: No module named 'tensorflow'

In [1]:
%pip install tensorflow --break-system-packages

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/26/a1/23b9b39c046c723db63a1c2c93397703efa3400a36f98d9c717b473aafb8/tensorflow-2.21.0-cp311-cp311-manylinux_2_27_x86_64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/58/0a/a10b45aab35b175aded078a462dc8d0c698f5b13946e7cb0869097b78bb6/absl_py-2.5.0-py3-none-any.whl.metadata
  Obtaining dependency information for astunparse>=1.6.0 from https://files.pythonhosted.org/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=25.9.23 from https://files.pythonhosted.org/packages/e8/2d/d2a548598be01649e2d46231d151a6c56d10b964d94043a335ae56ea2d92/flatbuffers-25.12.19-py2.py3-none-any.whl.metadata
  Obtaining dependency information for gast!=0.5.0

In [2]:
import tensorflow as tf
print(tf.__version__)


2.21.0


In [3]:
%pip install "numpy==1.26.4" --break-system-packages


Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for numpy==1.26.4 from https://files.pythonhosted.org/packages/3a/d0/edc009c27b406c4f9cbc79274d6e46d634d139075492ad055e3d68445925/numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 195.2 kB/s eta 0:00:001m982.8 kB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 4.7 MB/s eta 0:00:00m eta 0:00:010:01:01
  Attempting uninstall: numpy
    Found existing installation: numpy 2.4.6
    Uninstalling numpy-2.4.6:
      Successfully uninstalled numpy-2.4.6
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ml-dtypes 0.6.0 requires numpy>=2.

In [18]:
import tensorflow as tf
a=tf.constant([[[8]]])
print("\n",a)
b=tf.Variable(9)
print("\n",b)
c=tf.Variable([[3,4,5],[4,7,8]])
print(c)
d=tf.constant([[3,4,5],[4,7,8]])
print(d)
e=c.assign([[1,2,4],[4,7,6]])
print(c)



 tf.Tensor([[[8]]], shape=(1, 1, 1), dtype=int32)

 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=9>
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[3, 4, 5],
       [4, 7, 8]], dtype=int32)>
tf.Tensor(
[[3 4 5]
 [4 7 8]], shape=(2, 3), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 4],
       [4, 7, 6]], dtype=int32)>


In [37]:
import tensorflow as tf
a=tf.range(3,16,3)
print(a)
c=tf.fill((3,3),8)
print(c)
d=tf.zeros((2,3))
print(d)
f=tf.ones((3,3))
print(f)

tf.Tensor([ 3  6  9 12 15], shape=(5,), dtype=int32)
tf.Tensor(
[[8 8 8]
 [8 8 8]
 [8 8 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [132]:
import tensorflow as tf
a=tf.constant([[3,4,5,4],[4,5,6,3],[2,3,5,4]])
print(a)
print(a[1])
print(a[0])
print(a[2,2])
print(a[1,0])
print(a[2,1])
b=tf.transpose(a)
print(b)
print(a[1,0])
print(a[2:4])
print(a[1:,2:])
print(a[0:2,1:3])
print(a[-1:-2:-1,-3:-4:-1])
print(a[-1:-2:-1])
e=tf.constant([[2,3,4,5],[2,6,8,4],[3,6,9,1]])
x=tf.reverse(e,axis=[1,0])
print(x)


tf.Tensor(
[[3 4 5 4]
 [4 5 6 3]
 [2 3 5 4]], shape=(3, 4), dtype=int32)
tf.Tensor([4 5 6 3], shape=(4,), dtype=int32)
tf.Tensor([3 4 5 4], shape=(4,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(
[[3 4 2]
 [4 5 3]
 [5 6 5]
 [4 3 4]], shape=(4, 3), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([[2 3 5 4]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[6 3]
 [5 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[4 5]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor([[3]], shape=(1, 1), dtype=int32)
tf.Tensor([[2 3 5 4]], shape=(1, 4), dtype=int32)
tf.Tensor(
[[1 9 6 3]
 [4 8 6 2]
 [5 4 3 2]], shape=(3, 4), dtype=int32)


import tensorflow as tf
a=tf.constant([2,4,5,6])
print(tf.reshape(a))

In [153]:
import tensorflow as tf
a=tf.constant([2,4,5,6]) 
print(tf.reshape(a,(2,2)))
print(tf.reshape(a,(-1,2)))
print(tf.reshape(a,(1,-1)))
b=tf.constant([[2,3,4],[3,6,8],[5,6,8]])
print(tf.reshape(b,[-1]))
c=tf.constant([1,2,3])
d=tf.constant([3,4,5])
print(tf.add(c,d))
print(tf.subtract(c,d))
print(tf.multiply(c,d))
print(tf.divide(c,d))

tf.Tensor(
[[2 4]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 4]
 [5 6]], shape=(2, 2), dtype=int32)
tf.Tensor([[2 4 5 6]], shape=(1, 4), dtype=int32)
tf.Tensor([2 3 4 3 6 8 5 6 8], shape=(9,), dtype=int32)
tf.Tensor([4 6 8], shape=(3,), dtype=int32)
tf.Tensor([-2 -2 -2], shape=(3,), dtype=int32)
tf.Tensor([ 3  8 15], shape=(3,), dtype=int32)
tf.Tensor([0.33333333 0.5        0.6       ], shape=(3,), dtype=float64)


In [155]:
import tensorflow as tf
a=tf.constant([[2,3],[4,6],[6,8]])
b=tf.constant([[7,8],[3,9]])
c=tf.matmul(a,b)
print(c)


tf.Tensor(
[[ 23  43]
 [ 46  86]
 [ 66 120]], shape=(3, 2), dtype=int32)


In [169]:
import tensorflow as tf
a=tf.constant([[3,4],[5,6],[7,8]])
c=tf.reduce_mean(a)
print(c)
d=tf.reduce_sum(a)
print(d)
print(tf.reduce_max(a))
print("\n",tf.reduce_min(a))
print(tf.reduce_sum(a,axis=0))
print(tf.reduce_sum(a,axis=1))
print(tf.reduce_max(a,axis=1))

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(33, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)

 tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([15 18], shape=(2,), dtype=int32)
tf.Tensor([ 7 11 15], shape=(3,), dtype=int32)
tf.Tensor([4 6 8], shape=(3,), dtype=int32)


In [206]:
import torch 
a=torch.tensor(3)
print(a)
print(a.shape)
b=torch.tensor([23,4,5,67,81])
print(b)
print(b.shape)
print(b.size())
c=torch.tensor([[21,3,21,3,6],[4,5,65,8,7]])
print(c.numel())
d=torch.zeros(3,3)
print(d)
f=torch.ones(3,3,dtype=int)
print(f)
g=torch.full((3,3),32)
print(g)
h=torch.arange(2,35,8)
print(h)
print(h.dtype)
print(type(h))
y=torch.rand(3,3)
print(y)
print(torch.randn(2,3))

tensor(3)
torch.Size([])
tensor([23,  4,  5, 67, 81])
torch.Size([5])
torch.Size([5])
10
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])
tensor([[32, 32, 32],
        [32, 32, 32],
        [32, 32, 32]])
tensor([ 2, 10, 18, 26, 34])
torch.int64
<class 'torch.Tensor'>
tensor([[0.2676, 0.0929, 0.6765],
        [0.2904, 0.5350, 0.2797],
        [0.7003, 0.0923, 0.0518]])
tensor([[-0.6806, -0.3587, -1.0846],
        [ 0.1955, -0.8180, -1.0074]])


In [ ]:
import torch
